### ISSUE TITLE
Ограничение максимального количества игроков в комнате

### ISSUE THREAD

**Issue by MikhailFominykh** [cheetah-game-platform/platform#185]
### Зачем
Клиент рассчитан на определённый максимум игроков на карте. Если предел достигнут, для новых клиентов должна быть создана ещё одна комната.

### Как
Сервис матчмейкинга получает от игрового сервера адрес комнаты и уникальный идентификатор слота в ней. Клиент подключается к комнате с указанием идентификатора слота. Игровой сервер принимает подключение только если в комнате существует слот с таким идентификатором. Если клиент от комнаты отключается, его место сохраняется некоторое время чтобы клиент мог подключиться заново при проблемах с сетью.

**Comment by avkviring** [comment]
@flaamjab не стоит добавлять максимальное количество игроков в конфиг комнаты, комната тут вообще не при чем. 
Это надо делать на уровне MatchMaking-а

Слоты тоже не надо - они и сейчас есть, как раз когда matchmaking создает в realtime сервере пользователя - это и есть аналог слота. Сохранение места тоже есть - 10 секунд дается клиенту для перезахода.

В итоге - надо добавить код StubMathmaking - чтобы он создавал новую битву если уже в созданных битвах больше N игроков
